// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: jupiter/proto/hugotransmission.proto

package xgrpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupiter_proto_hugotransmission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_jupiter_proto_hugotransmission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_jupiter_proto_hugotransmission_proto_rawDescGZIP(), []int{0}
}

// 设置默认的请求数据传输
type HugoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//请求id
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	//接口名称
	InterfaceName string `protobuf:"bytes,2,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`
	//方法名称
	MethodName string `protobuf:"bytes,3,opt,name=methodName,proto3" json:"methodName,omitempty"`
	//方法参数 repeated 定义类似集合
	//map<string, Bar>  parameters = 4;
	//参数类型 repeated 定义类似集合
	//repeated string paramTypes =5;
	//map<string, Bar>  paramTypes = 5;
	//方法参数 repeated 定义类似集合
	Parameters []string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	//参数类型 repeated 定义类似集合
	ParamTypes []string `protobuf:"bytes,5,rep,name=paramTypes,proto3" json:"paramTypes,omitempty"`
}

func (x *HugoRequest) Reset() {
	*x = HugoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupiter_proto_hugotransmission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HugoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HugoRequest) ProtoMessage() {}

func (x *HugoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jupiter_proto_hugotransmission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HugoRequest.ProtoReflect.Descriptor instead.
func (*HugoRequest) Descriptor() ([]byte, []int) {
	return file_jupiter_proto_hugotransmission_proto_rawDescGZIP(), []int{1}
}

func (x *HugoRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HugoRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *HugoRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *HugoRequest) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *HugoRequest) GetParamTypes() []string {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

// The response message containing the greetings
// 设置默认的返回
type HugoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//请求id
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	//返回的结果默认是200，成功
	Code int32 `protobuf:"zigzag32,2,opt,name=code,proto3" json:"code,omitempty"`
	//消息默认是成功
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	//数据默认是null
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HugoResponse) Reset() {
	*x = HugoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jupiter_proto_hugotransmission_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HugoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HugoResponse) ProtoMessage() {}

func (x *HugoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jupiter_proto_hugotransmission_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HugoResponse.ProtoReflect.Descriptor instead.
func (*HugoResponse) Descriptor() ([]byte, []int) {
	return file_jupiter_proto_hugotransmission_proto_rawDescGZIP(), []int{2}
}

func (x *HugoResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HugoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HugoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HugoResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_jupiter_proto_hugotransmission_proto protoreflect.FileDescriptor

var file_jupiter_proto_hugotransmission_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6a, 0x75, 0x70, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x68, 0x75, 0x67, 0x6f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x75, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x05, 0x0a, 0x03, 0x42, 0x61, 0x72, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x48, 0x75, 0x67,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x0c,
	0x48, 0x75, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0d, 0x5a, 0x0b,
	0x2e, 0x3b, 0x68, 0x75, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jupiter_proto_hugotransmission_proto_rawDescOnce sync.Once
	file_jupiter_proto_hugotransmission_proto_rawDescData = file_jupiter_proto_hugotransmission_proto_rawDesc
)

func file_jupiter_proto_hugotransmission_proto_rawDescGZIP() []byte {
	file_jupiter_proto_hugotransmission_proto_rawDescOnce.Do(func() {
		file_jupiter_proto_hugotransmission_proto_rawDescData = protoimpl.X.CompressGZIP(file_jupiter_proto_hugotransmission_proto_rawDescData)
	})
	return file_jupiter_proto_hugotransmission_proto_rawDescData
}

var file_jupiter_proto_hugotransmission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jupiter_proto_hugotransmission_proto_goTypes = []interface{}{
	(*Bar)(nil),          // 0: hugo_grpc.Bar
	(*HugoRequest)(nil),  // 1: hugo_grpc.HugoRequest
	(*HugoResponse)(nil), // 2: hugo_grpc.HugoResponse
}
var file_jupiter_proto_hugotransmission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jupiter_proto_hugotransmission_proto_init() }
func file_jupiter_proto_hugotransmission_proto_init() {
	if File_jupiter_proto_hugotransmission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jupiter_proto_hugotransmission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupiter_proto_hugotransmission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HugoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jupiter_proto_hugotransmission_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HugoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jupiter_proto_hugotransmission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jupiter_proto_hugotransmission_proto_goTypes,
		DependencyIndexes: file_jupiter_proto_hugotransmission_proto_depIdxs,
		MessageInfos:      file_jupiter_proto_hugotransmission_proto_msgTypes,
	}.Build()
	File_jupiter_proto_hugotransmission_proto = out.File
	file_jupiter_proto_hugotransmission_proto_rawDesc = nil
	file_jupiter_proto_hugotransmission_proto_goTypes = nil
	file_jupiter_proto_hugotransmission_proto_depIdxs = nil
}
